<?php
namespace common\modules\chat\controllers;
use common\modules\chat\models\Chat;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class BasicController extends Controller
{

    /**
     * Сообщение об ошибке
     *
     * @var
     */
    public $msg;
    /**
     * Наличие ошибки
     *
     * @var
     */
    public $error;

    /**
     * Код ошибки
     *
     * @var int
     */
    public $error_type = 0;

    /**
     * Данные к выдаче
     *
     * @var
     */
    public $data;

    public $user;

    public function init()
    {
        $this->user = Yii::$app->user->getIdentity();
        parent::init(); // TODO: Change the autogenerated stub
    }




    public function actionIndex()
    {
        return $this->render('form');
    }

    public function actionGet_message()
    {
        $this->init_ajax();
        if ($this->user->isAdmin) {
            $models = Chat::find()->all();
        } else {
            $models = Chat::find()->where(['status'=>Chat::STATUS_CORRECT])->all();
        }
        $this->error = 'no';
        $this->data = Yii::$app->view->renderAjax('@common/modules/chat/views/basic/table_mess.php',['models'=>$models]);
        return $this->out();
    }

    public function actionSet_message()
    {
        $this->init_ajax();
        $model = new Chat();
        $model->msg = Yii::$app->request->post('msg');
        $model->user_id = Yii::$app->user->identity->id;
        if ($model->validate()) {
            $model->save();
            $this->error = 'no';
            $this->msg = 'Сообщение успешно отправлено';

        } else {
            $errors = '';
            foreach ($model->getErrors() as $key => $value) {
                $errors = $key.': '.$value[0];
            }
            $this->error = 'yes';
            $this->msg = $errors;
        }
        return $this->out();
    }



    //---------------------------------------------------- AJAX ----------------------------------------//
    /**
     * Стандартная выдача сообщений
     *
     * @return array
     */
    public function out()
    {
        return ['error'=>$this->error, $this->error_type,'msg'=>$this->msg, 'data'=> ($this->error=='no') ? $this->data : '' ];
    }

    /**
     * Базовая инициализация
     */
    public function init_ajax()
    {
        $this->error = 'yes';
        $this->msg = 'Ошибка';
        Yii::$app->response->format = Response::FORMAT_JSON;
    }
    //---------------------------------------------------- END AJAX ----------------------------------------//
}